#ifndef __CONFIG_HPP__
#define __CONFIG_HPP__

#define ADDR_ALIGNMENT_SIZE 4 // 地址对齐方式

#define VARIABLE_NAME_STR_LENGTH_MAX 100 // 名称字符串最大长度

#define A2L_TYPE_STR_LENGTH_MAX 100  // A2L类型字符串最大长度
#define A2L_LIMIT_STR_LENGTH_MAX 100 // A2L限制字符串最大长度

#define SEGMENT_BUFF_LENGTH 5000 // 段缓冲区长度

// 输出文件默认前缀
#define OUTPUT_A2L_PREFIX "[NEW]"
// 中间件尾缀
#define OUTPUT_MIDDLEWARE_SUFFIX ".middleware.txt"
// 中间件默认名称
#define OUTPUT_DEFAULT_MIDDLEWARE_FILE_NAME "Middleware.txt"

// 相关识别串
#define START_OF_MEASURMENT_PATTERN_STR "/*start_of_measurements*/"
#define END_OF_MEASURMENT_PATTERN_STR "/*end_of_measurements*/"
#define START_OF_CALIBRATION_PATTERN_STR "/*start_of_calibrations*/"
#define END_OF_CALIBRATION_PATTERN_STR "/*end_of_calibrations*/"

// A2L 插入识别串
#define A2L_INSERT_PATTERN_STR "/end MODULE"

// 段输出标识串

#define START_OF_GENERATED_RECORD_LAYOUT_STR "/***********   start of record layout block generated by SrcToA2L   ***********/"
#define END_OF_GENERATED_RECORD_LAYOUT_STR "/***********   end of record layout block generated by SrcToA2L   ***********/"

#define START_OF_GENERATED_CALIBRATION_AND_MEASURMENT_STR "/***********   start of calibrations and measurements block generated by SrcToA2L   ***********/"
#define END_OF_GENERATED_CALIBRATION_AND_MEASURMENT_STR "/***********   end of calibrations and measurements block generated by SrcToA2L    ***********/"

#endif